### ISSUE TITLE
The Width of Image

### ISSUE THREAD

**Issue by fiik346** [verlok/vanilla-lazyload#499]
if I add css 
```css
img {max-width: 100%; width: 100%; height: auto;}
```
 will the image be loaded according to the width of the element? Like the lazysizes data-sizes = "auto" feature?
