### ISSUE TITLE
Lazy loading background images without inline style (With sollution)

### ISSUE THREAD

**Issue by somegooser** [verlok/vanilla-lazyload#550]
Hi,

I have a problem with not able to add inline style for lazyloading background images. So i would like to add the feature to use lazy loading background images with CSS Var values.

Example:

```css
.lazy {
    height: 500px;
    width: 100%;
   --data-background-image: url('https://domain.com/images/example.jpg');
}
```

**Comment by verlok** [comment]
Hey @somegooser 
sorry I forgot to reply but your “with solution” in the title sounded like a suggestion for other users and not like a question to me. 

Do you still need help with this issue?
If not, how did you solve?

**Comment by somegooser** [comment]
Hi solved it by using the loaded class and made my own implementation like this:

```css
.lazy-div:not(.loaded) {
     background-image: none !important;
}
```
