### ISSUE TITLE
An option to keep the initial src value on a loading error

### ISSUE THREAD

**Issue by ExLuzZziVo** [verlok/vanilla-lazyload#562]
Hello,

Is it possible to add an option to keep the initial src value on a loading error?

For example, it can be used for placeholders with predefined sizes to easily display a loading indicator and an error:

```html
<img
  src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'%3E%3C/svg%3E"
  data-src="/images/1.jpg"
  class="img-fluid lazy"
/>
```

```css
.lazy-loading-indicator {
    background-color: white;
    background-image: url(/images/loading.gif);
    background-position: center;
    background-repeat: no-repeat;
}

.lazy-loading-error {
    background-color: white;
    background-image: url(/images/error.jpg);
    background-position: center;
    background-repeat: no-repeat;
}
```

```js
const lazyLoad = new LazyLoad({
    class_loading: "lazy-loading-indicator",
    class_error: "lazy-loading-error"
)};
```

Thank you
